LearnMode: True
AMinerUser: 'aminer'
AMinerGroup: 'aminer'

LogResourceList:
        #- 'file:///home/ubuntu/data/mail.cup.com-train/daemon.log'
        #- 'file:///home/ubuntu/data/mail.cup.com-train/auth.log'
        #- 'file:///home/ubuntu/data/mail.cup.com-train/suricata/eve.json'
        #- 'file:///home/ubuntu/data/mail.cup.com-train/suricata/fast.log'
        - 'file:///home/ubuntu/data/mail.cup.com-test/apache2/mail.cup.com-access.log'
        #- 'file:///home/ubuntu/data/mail.cup.com-train/apache2/mail.cup.com-error.log'
        #- 'file:///home/ubuntu/data/mail.cup.com-test/exim4/mainlog'
        #- 'file:///home/ubuntu/data/mail.cup.com-train/syslog'
        #- 'file:///home/ubuntu/data/mail.cup.com-test/audit/audit.log'

# Read and store information to be used between multiple invocations
# of AMiner in this directory. The directory must only be accessible
# to the 'AMinerUser' but not group/world readable. On violation,
# AMiner will refuse to start. When undefined, '/var/lib/aminer'
# is used.
# Core.PersistenceDir: '/tmp/lib/aminer'

# Define a target e-mail address to send alerts to. When undefined,
# no e-mail notification hooks are added.
# MailAlerting.TargetAddress: 'root@localhost'

# Sender address of e-mail alerts. When undefined, "sendmail"
# implementation on host will decide, which sender address should
# be used.
# MailAlerting.FromAddress: 'root@localhost'

# Define, which text should be prepended to the standard aminer
# subject. Defaults to "AMiner Alerts:"
# MailAlerting.SubjectPrefix: 'AMiner Alerts:'

# Define a grace time after startup before aminer will react to
# an event and send the first alert e-mail. Defaults to 0 (any
# event can immediately trigger alerting).
# MailAlerting.AlertGraceTime: 0

# Define how many seconds to wait after a first event triggered
# the alerting procedure before really sending out the e-mail.
# In that timespan, events are collected and will be sent all
# using a single e-mail. Defaults to 10 seconds.
# MailAlerting.EventCollectTime: 10

# Define the minimum time between two alert e-mails in seconds
# to avoid spamming. All events during this timespan are collected
# and sent out with the next report. Defaults to 600 seconds.
# MailAlerting.MinAlertGap: 600

# Define the maximum time between two alert e-mails in seconds.
# When undefined this defaults to "MailAlerting.MinAlertGap".
# Otherwise this will activate an exponential backoff to reduce
# messages during permanent error states by increasing the alert
# gap by 50% when more alert-worthy events were recorded while
# the previous gap time was not yet elapsed.
# MailAlerting.MaxAlertGap: 600

# Define how many events should be included in one alert mail
# at most. This defaults to 1000
# MailAlerting.MaxEventsPerMessage: 1000

# Configure the logline prefix
# LogPrefix: ''

Parser:
        - id: 'auditModel'
          type: AuditdParsingModel
          name: 'audit'
          args: 'audit'

        - id: 'suricataEventModel'
          type: SuricataEventParsingModel
          name: 'suricataEvent'
          args: 'suricataEvent'

        - id: 'syslogModel'
          type: SyslogParsingModel
          name: 'syslog'
          args: 'syslog'

        - id: 'apacheAccessModel'
          type: ApacheAccessParsingModel
          name: 'apacheAccess'
          args: 'apacheAccess'

        - id: 'apacheErrorModel'
          type: ApacheErrorParsingModel
          name: 'apacheError'
          args: 'apacheError'

        - id: 'eximModel'
          type: EximParsingModel
          name: 'exim'
          args: 'exim'

        - id: 'suricataFastModel'
          type: SuricataFastParsingModel
          name: 'suricataFast'
          args: 'suricataFast'

        - id: 'START'
          start: True
          type: FirstMatchModelElement
          name: 'parser'
          args:
            - auditModel
            - suricataEventModel
            - syslogModel
            - apacheAccessModel
            - apacheErrorModel
            - eximModel
            - suricataFastModel

Input:
        verbose: True
        multi_source: True
        timestamp_paths: 
          - '/parser/model/time'
          - '/parser/model/type/execve/time'
          - '/parser/model/type/proctitle/time'
          - '/parser/model/type/syscall/time'
          - '/parser/model/type/path/time'
          - '/parser/model/type/login/time'
          - '/parser/model/type/sockaddr/time'
          - '/parser/model/type/unknown/time'
          - '/parser/model/type/cred_refr/time'
          - '/parser/model/type/user_start/time'
          - '/parser/model/type/user_acct/time'
          - '/parser/model/type/user_auth/time'
          - '/parser/model/type/cred_disp/time'
          - '/parser/model/type/service_start/time'
          - '/parser/model/type/service_stop/time'
          - '/parser/model/type/user_end/time'
          - '/parser/model/type/cred_acq/time'
          - '/parser/model/type/user_bprm_fcaps/time'


Analysis:
         - type: 'ParserCount'
           paths:
            - '/parser/model/type_str' # Audit
            - '/parser/model/status_code' # Apache Access
            - '/parser/model/php' # Apache Error
            - '/parser/model/sp' # Exim
            - '/parser/model/event_type_str' # Suricata Event
            - '/parser/model/classification' # Suricata Fast
            - '/parser/model/host' # Syslog
           report_interval: 10
           reset_after_report_flag: False
           learn_mode: True

         - type: 'NewMatchPathValueDetector'
           paths: ['/parser/model/status_code']
           persistence_id: 'accesslog_status'
           output_logline: False
           learn_mode: True

         - type: 'NewMatchPathValueComboDetector'
           paths: ['/parser/model/fm/request/method', '/parser/model/combined/combined/user_agent']
           persistence_id: 'accesslog_request_agent'
           output_logline: False
           allow_missing_values: False
           learn_mode: True

         #- type: 'EventCorrelationDetector'
         #  paths: ['/parser/model/fm/request/method', '/parser/model/fm/request/request']
         #  max_observations: 200
         #  hypothesis_max_delta_time: 10.0
         #  hypotheses_eval_delta_time: 28800.0
         #  delta_time_to_discard_hypothesis: 28800.0
         #  p0: 0.95
         #  alpha: 0.05
         #  check_rules_flag: False
         #  persistence_id: 'accesslog_method_request'
         #  learn_mode: True

         #- type: 'NewMatchPathValueComboDetector'
         #  paths: ['/parser/model/type/syscall/syscall', '/parser/model/type/syscall/uid', '/parser/model/type/syscall/comm', '/parser/model/type/syscall/exe']
         #  learn_mode: False
         #  persistence_id: 'audit_syscall_uid_comm_exe'
         #  output_logline: False
         #  allow_missing_values: False

EventHandlers:
        - id: 'stpe'
          json: True # optional default: False
          type: 'StreamPrinterEventHandler'
